name: Commitlint
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }
      - uses: wagoid/commitlint-github-action@v6
        continue-on-error: true
