name: Link Check
on:
  pull_request:
    paths:
      - "README.md"
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --max-redirects 10 --exclude-mail --accept 200,203,206,302,303,307,308,429,500 --timeout 20 --retry 2 --retry-wait 2 README.md
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
