name: Link Check
on:
  pull_request:
  push:
    branches: [ "main" ]
    paths:
      - "README.md"
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --accept 200,203,206,302,303,307,308 README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
