name: Lock closed issues
on:
  schedule:
    - cron: "0 3 * * *"
jobs:
  lock:
    permissions: { issues: write, pull-requests: write }
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          issue-inactive-days: 14
          pr-inactive-days: 14
