name: Release Drafter
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, closed]
jobs:
  draft:
    permissions: { contents: write, pull-requests: write }
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
