name: Release artifacts
on:
  push:
    tags:
      - "v*"
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: "lts/*" }
      - name: Build minified (release-only)
        run: |
          npm i -g esbuild
          mkdir -p dist
          [ -f Auto-Farm.js ] && esbuild Auto-Farm.js --minify --legal-comments=none --outfile=dist/Auto-Farm.min.js
          [ -f Auto-Image.js ] && esbuild Auto-Image.js --minify --legal-comments=none --outfile=dist/Auto-Image.min.js
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Auto-Farm.min.js
            dist/Auto-Image.min.js
