name: Release Drafter
on:
  push:
    branches: [ "main" ]
jobs:
  draft:
    permissions: { contents: write, pull-requests: write }
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
