name: Semantic PRs
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
jobs:
  check:
    permissions: { pull-requests: read, statuses: write }
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat, fix, chore, docs, refactor, perf, ci, test, build
