name: Mark stale issues and PRs
on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  stale:
    permissions: { issues: write, pull-requests: write }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 45
          days-before-close: -1
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "pinned,security"
          stale-issue-message: "Este issue lleva tiempo sin actividad. Por favor, comenta si sigue vigente."
          stale-pr-message: "Este PR lleva tiempo sin actividad. Por favor, comenta si sigue vigente."
