name: Mark stale issues and PRs
on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  stale:
    permissions: { issues: write, pull-requests: write }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "pinned,security"
          stale-issue-message: "Este issue lleva 30 días sin actividad. Se cerrará si no hay novedades."
          stale-pr-message: "Este PR lleva 30 días sin actividad. Se cerrará si no hay novedades."
