name: Super Linter
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v5
        with:
          # Fetch full history for better Super-Linter compatibility
          fetch-depth: 0
      - name: Lint code base
        uses: super-linter/super-linter@v8
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_ALL_CODEBASE: false
          # Configuración de filtros - múltiples estrategias
          FILTER_REGEX_EXCLUDE: ".*Auto-Farm\\.js|.*Auto-Guard\\.js|.*Auto-Image\\.js|.*Auto-Launcher\\.js|.*dist/.*|.*node_modules/.*|.*src/core/turnstile\\.js|.*src/log_window/log-window\\.js"
          JAVASCRIPT_ES_FILE_NAME: "eslint.config.js"
          # Usar solo el código fuente para validación
          FILTER_REGEX_INCLUDE: ".*src/.*\\.js$|.*eslint\\.config\\.js$|.*package\\.json$"
          # Don't fail the workflow on lint errors; just report status
          IGNORE_GITIGNORED_FILES: true
        continue-on-error: true
